project: qSSm
program: training.py
method: random # bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  #kernel_quant:
  #  values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  linear_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  A_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  B_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  C_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  dt_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  act_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  coder_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  #all_quant:
  #  values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  state_quant:
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]

command:
  - ${env}
  - python
  - ${program}
  - "--sw"
  - True
  - "--grayscale"
  - "--dataset"
  - cifar10 
  - "--wb"
  - online
  - ${args}
